import { Inter } from "next/font/google";
import "./globals.css";
import { TasksProvider } from "./context/TaskContext";

const inter = Inter({
  subsets: ["latin-ext"],
  weights: [400, 500, 600, 700],
  display: "swap",
  variable: "font- ",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} antialiased w-screen h-screen `}>
        <TasksProvider>{children}</TasksProvider>
      </body>
    </html>
  );
}
